version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: javac src/Main.java
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloudTest
